site_name: QubiPy
repo_url: https://github.com/QubiPy-Labs/QubiPy
repo_name: QubiPy
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - RPC Client: rpc.md
  - Core Client: core.md
  - Advanced examples: examples.md
  - Security & Best practices: security.md
  - Contributions: contributing.md
  - Code of conduct: code_of_conduct.md
  - Changelog: changelog.md
  - About: about.md

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - mkdocstrings:
      handlers:
        python:
          paths: [../qubipy]
          options:
            show_source: false
            show_root_heading: true
  - git-revision-date-localized:
      enable_creation_date: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QubiPy-Labs/QubiPy
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EejFQdQkhG

copyright: Made with ❤️ by QubiPy Labs
extra:
  generator: false