site_name: QubiPy
repo_url: https://github.com/QubiPy-Labs/QubiPy
repo_name: QubiPy
theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
  
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - RPC Client: rpc.md
  - Core Client: core.md
  - Advanced examples: examples.md
  - Security & Best practices: security.md
  - Contributions: contributing.md
  - Code of conduct: code_of_conduct.md
  - Changelog: changelog.md
  - About: about.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../qubipy]

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QubiPy-Labs/QubiPy
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EejFQdQkhG