blank_issues_enabled: false 
contact_links:
  - name: QubiPy Discord Community
    url: https://discord.gg/EejFQdQkhG
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://qubipy.readthedocs.io
    about: Check our documentation for guides and information.